### PR TITLE
Fix: Copy URL button disabling.

### PR DESCRIPTION
**Pull request by bhushansshah**
## Pull Request Checklist

Before submitting a pull request, please make sure that your changes meet the following criteria:

- [x] Ensure that your code adheres to our coding conventions and is properly formatted.
- [x] Test your changes extensively to ensure that they do not introduce any new bugs.
- [x] Confirm that you agree to the code of conduct.

## Link to the Resolved Issue

Copy URL button should be disabled on the landing page

Fixes https://github.com/OpenSource-Journey/Your-Github-Contributions/issues/60

## Screenshots
Copy URL button is disabled when there is not text in the input.

Screenshot from 2023-03-25 20-19-28

Copy URL button is enabled when there is some content in the input.

Screenshot from 2023-03-25 20-19-43

### CODE REVIEW

**Review by anuj-kumary — CHANGES_REQUESTED** [review]
Hey, @bhushansshah no need to update the readme after PR merged we have setup bot it will automatically update readme.
Can you please revert your changes.

**Comment by bhushansshah** [comment]
Hi @anuj-kumary, I have made the requested changes.

**Review by anuj-kumary — APPROVED** [review]
Thanks for the contributions @bhushansshah ✨

**Review by Sachin-chaurasiya — APPROVED** [review]
Great work @bhushansshah  🙌🏻,
Thanks for the contributions ✨

**Comment by Sachin-chaurasiya** [comment]
@all-contributors please add @bhushansshah for Code

**Pull request merged**
