### PR TITLE
removed copy url button from home page

### LINKED ISSUE #37: [Bug]:  The "Copy URL" button on the home page is not necessary
### What happened?

We have a "Copy URL" button on both the home page and the summary page. However, the "Copy URL" button on the home page is unnecessary and should be removed.

### Please provide an bug screenshot

image

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Hat52**
## Pull Request Checklist

Before submitting a pull request, please make sure that your changes meet the following criteria:

- [x] Ensure that your code adheres to our coding conventions and is properly formatted.
- [x] Test your changes extensively to ensure that they do not introduce any new bugs.
- [x] Confirm that you agree to the code of conduct.

## Related Issues

Closes #37 

## Screenshots
image

## Additional Notes

No

### CODE REVIEW

**Comment by Sachin-chaurasiya** [comment]
Hello @Hat52 , thanks for the PR.


Build is failing due to some linting errors can you check?

**Comment by Sachin-chaurasiya** [comment]
Hello @Hat52, Any progress on this PR?

**Comment by Hat52** [comment]
Hello @Sachin-chaurasiya , I had an emergency
 going on at home. Hope fully I will update it tomorrow

**Comment by Sachin-chaurasiya** [comment]
> Hello @Sachin-chaurasiya , I had an emergency going on at home. Hope fully I will update it tomorrow

No worries @Hat52, Take care.

**Comment by Hat52** [comment]
I am getting 

> ✖ Prevented an empty git commit!

error from husky webhook. The suggestion says that I should add --allow-empty in my command.

Should I go with it or is there  a better way?

**Comment by Sachin-chaurasiya** [comment]
> I am getting
> 
> > ✖ Prevented an empty git commit!
> 
> error from husky webhook. The suggestion says that I should add --allow-empty in my command.
> 
> Should I go with it or is there a better way?

Hello @Hat52 , Sorry for the late response, please take the latest pull and then try.
Also, if you are trying to make empty commit then it won't work.

**Comment by Hat52** [comment]
I have rebased this branch with main branch and pushed it. @Sachin-chaurasiya

**Comment by Sachin-chaurasiya** [comment]
> I have rebased this branch with main branch and pushed it. @Sachin-chaurasiya

Hello @Hat52, apologies for the late response. build is failing with this error can you fix it?
image

**Comment by Sachin-chaurasiya** [comment]
Due to inactivity closing this PR.

**Pull request closed without merging**
